const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const C=require('./core.js');
test('legacy records migrate without modifying the original',()=>{const raw={tags:['胶水','迷雾','无法开口','<script>'],batteryIdx:3,pressure:{chest:67,head:41,limbs:13}},before=JSON.stringify(raw),s=C.migrate(raw);assert.equal(s.texture,'胶水');assert.deepEqual(s.feelings,['无法开口']);assert.equal(s.energy,88);assert.equal(s.pressure.chest,67);assert.equal(JSON.stringify(raw),before);});
test('malformed storage values are bounded and unknown tokens excluded',()=>{const s=C.normalize({texture:'<img>',feelings:['想蜷缩','想蜷缩',null],energy:Infinity,pressure:{chest:-5,head:300,limbs:2.7},supports:['__proto__','company'],note:'a'.repeat(800)});assert.equal(s.texture,'');assert.deepEqual(s.feelings,['想蜷缩']);assert.equal(s.energy,50);assert.deepEqual(s.pressure,{chest:0,head:100,limbs:3});assert.deepEqual(s.supports,['company']);assert.equal(s.note.length,500);});
test('every material has multiple different, contextual poems',()=>{const all=new Set();for(const [texture] of C.textures){const s=C.normalize({texture,feelings:['无法开口']});const variants=Array.from({length:9},(_,i)=>C.poem(s,i));assert.ok(new Set(variants).size>=6,texture);assert.ok(variants.every(p=>p.includes('开不了口')));assert.ok(C.poetry[texture].material);all.add(variants[0]);}assert.equal(all.size,10);});
test('doctor notes report inputs rather than inventing clinical severity',()=>{const s=C.normalize({texture:'沉重',pressure:{chest:99},duration:'几天',note:'上楼时不舒服'});const report=C.doctorCard(s);assert.match(report,/胸口压迫感：99/);assert.match(report,/几天/);assert.match(report,/上楼时不舒服/);assert.doesNotMatch(report,/精神运动性抑制|疑似|重度抑郁/);});
test('friend cards include only selected requests and optional physical information',()=>{const s=C.normalize({texture:'迷雾',supports:['message'],pressure:{chest:70}});const card=C.friendCard(s);assert.match(card,/文字和我联系/);assert.doesNotMatch(card,/胸口|晚上 8|独处时间/);s.includeBody=true;assert.match(C.friendCard(s),/胸口压得很难受/);});
test('risk language is never randomized away and produces an actionable message',()=>{const s=C.normalize({feelings:['无法开口','想消失'],energy:5});assert.equal(C.needsSafetyCheck(s),true);assert.match(C.poem(s,0),/退开的念头/);assert.match(C.poem(s,7),/退开的念头/);assert.match(C.friendCard(s,'thoughts'),/伤害自己的想法/);assert.match(C.friendCard(s,'thoughts'),/请现在回复或联系我/);});
test('doctor summary includes functioning and explicit safety context',()=>{const s=C.normalize({feelings:['想消失'],functioning:'几乎无法维持日常生活'}),card=C.doctorCard(s,'safe');assert.match(card,/几乎无法维持日常生活/);assert.match(card,/目前没有伤害自己的打算/);});
test('edited drafts including intentionally empty drafts survive normalization',()=>{const s=C.normalize({friendDraft:'我的手写文字',doctorDraft:''});assert.equal(s.friendDraft,'我的手写文字');assert.equal(s.doctorDraft,'');});
test('breath phase boundary aligns with countdown and completed cycles',()=>{assert.equal(C.breathAt(3999).label,'吸气');assert.equal(C.breathAt(4000).label,'呼气');assert.equal(C.breathAt(4000).remaining,6);assert.equal(C.breathAt(10000).cycles,1);assert.equal(C.breathAt(4000,'classic').label,'停留');assert.equal(C.breathAt(8000,'classic').label,'呼气');assert.equal(C.breathAt(12000,'classic').cycles,1);assert.equal(C.breathAt(4000,'classic').scale,1.1);});
function canvasContext(){let ops=[];return {ops,context:new Proxy({measureText:t=>({width:[...t].length*14}),createRadialGradient:()=>({addColorStop(){}}),createLinearGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]??((...args)=>{for(const a of args)if(typeof a==='number')assert.ok(Number.isFinite(a),k);ops.push([k,...args]);}),set:(o,k,v)=>{o[k]=v;return true;}})};}
test('all ten renderers execute at phone/desktop dimensions with distinct geometry',()=>{const context={};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'visual.js'),'utf8'),context);for(const [w,h]of [[335,295],[600,450]]){const signatures=new Set();for(const [name]of C.textures){const {context:ctx,ops}=canvasContext();context.EchoVisual.draw(ctx,w,h,9,name,.8);assert.ok(ops.length>10);signatures.add(JSON.stringify(ops));}assert.equal(signatures.size,10);}});
test('petrified material stays static while flowing materials change over time',()=>{const v={};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'visual.js'),'utf8'),v);function render(name,time){const c=canvasContext();v.EchoVisual.draw(c.context,500,400,time,name,0);return JSON.stringify(c.ops);}assert.equal(render('石化',0),render('石化',10));for(const name of ['胶水','噪点','失重','空洞','溺水','碎玻璃'])assert.notEqual(render(name,0),render(name,10),name);});
test('HTML wiring has unique ids and scripts refer only to existing or generated elements',()=>{const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8'),app=fs.readFileSync(path.join(__dirname,'app.js'),'utf8');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);for(const m of app.matchAll(/\$\('([^']+)'\)/g)){if(m[1].endsWith('-'))continue;assert.ok(ids.includes(m[1]),m[1]);}for(const file of ['core.js','visual.js','app.js'])new vm.Script(fs.readFileSync(path.join(__dirname,file),'utf8'));});

